version: "3"

services: 
  valheim: 
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $SERVER_VOLUME/config:/config
      - $SERVER_VOLUME/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $SERVER_VOLUME/config/valheim.env
    restart: always
    stop_grace_period: 2m
